### ISSUE TITLE
Check marks don't persist when using the `include plugin`.

### ISSUE THREAD

**Issue by dwightmulcahy** [leibler/dokuwiki-plugin-todo#174] opened 2024-05-26 20:07 UTC
I'm using the [ Include Plugin](https://www.dokuwiki.org/plugin:include)

```
==== Travel Plans ====

{{page>journal:travel_@YEAR@&inline&noindent&nofooter}}

```

Here is `journal:travel_2024`:
```
//**5/27-28/2024**//: //IL Trip//
<todo>Book flight</todo>
<todo>Book room</todo>

//**6/20-24/2024**//: //Disney Trip//
<todo>Book flight</todo>
<todo>Book room</todo>
```

The check isn't saved when I check off any of the ToDos on the main page from the including page with the ToDos on it.

I use the `inline` option, but it doesn't work.

**Comment by runout-at** [comment] 2024-05-26 22:57
Duplicate of #135

**Closed by runout-at** 2024-05-26 22:57 UTC
Labels: duplicate, wontfix
