### ISSUE TITLE
Finished todos to be deleted in source code

### ISSUE THREAD

**Issue by virk** [leibler/dokuwiki-plugin-todo#103] opened 2018-08-18 16:54 UTC
I am using the "todo"-plugin for managing tasks. Unfortunately there is no possibility (or I do not know about it) to automatically delete tasks in the source code, when they are finished. This means that they stay on the page where I put them and they make the page more "unreadable".

What I am thinking about: I write a todo on a page (or even better I do not need to go into edit mode :-) )and as soon as I have "clicked" this task being finished, it disappears (also) in the source code of the page and is no longer stored anywhere.

This would make the plugin nicer in my eyes.

**Comment by runout-at** [comment] 2019-03-10 19:55
this way you would loose the information when the task was finished/checked - this is not intended behaviour.
i don't see an easy way to delete todos automatically without loosing information accidently/easily.
you would loose the list of tasks which had to be done at all.

**Comment by einhirn** [comment] 2020-02-14 14:01
You could just use a plugin like https://www.dokuwiki.org/plugin:batchedit to do that, or maybe change CSS so that checked TODOs aren't shown anymore...
Anyway, WONTFIX.

**Closed by einhirn** 2020-02-14 14:01 UTC
Labels: wontfix
