### ISSUE TITLE
Ignore template pages for todolist

### ISSUE THREAD

**Issue by Braintelligence** [leibler/dokuwiki-plugin-todo#50] opened 2015-03-12 21:20 UTC
Hi there,

it would be nice if you'd be able to ignore page templates when listing all todos. That way you can use pre-defined todos in page templates without seeing them in a todolist.

**Comment by runout-at** [comment] 2015-03-14 08:25
i close this as a duplicate of #49

**Closed** 2015-03-14 08:25 UTC
